In [1]:
%matplotlib inline

import pandas as pd
import numpy as np

In [39]:
import pandas as pd
import numpy as np

In [40]:
df=pd.read_csv('final.csv')

In [41]:
df.set_index('date')
df=df.iloc[1:]

In [42]:
df

,date,content_score,desc_score,title_score,Open,High,Low,Close,Adj Close,Volume,change_close
1,2018-09-25,0.044822,0.161199,0.111867,219.750000,222.820007,219.699997,222.190002,221.417435,24554400,1.400009
2,2018-09-26,-0.043366,0.063646,0.091782,221.000000,223.750000,219.759995,220.419998,219.653595,23984700,-1.770004
3,2018-09-27,0.067147,0.207833,0.092848,223.820007,226.440002,223.539993,224.949997,224.167831,30181200,4.529999
4,2018-09-28,0.061063,0.112903,0.112483,224.789993,225.839996,224.020004,225.740005,224.955093,22929400,0.790008
5,2018-10-01,0.053996,0.051756,0.029758,227.949997,229.419998,226.350006,227.259995,226.469803,23600800,1.519990
6,2018-10-02,0.091796,0.109139,0.077273,227.250000,230.000000,226.630005,229.279999,228.482788,24788200,2.020004
7,2018-10-03,0.103879,0.158083,0.056533,230.050003,233.470001,229.779999,232.070007,231.263092,28654800,2.790008
8,2018-10-04,0.037060,0.138439,0.064772,230.779999,232.350006,226.729996,227.990005,227.197281,32042000,-4.080002
9,2018-10-05,0.028122,0.093663,0.052331,227.960007,228.410004,220.580002,224.289993,223.510132,33580500,-3.700012
10,2018-10-08,0.047460,0.110403,0.194308,222.210007,224.800003,220.199997,223.770004,222.991943,29663900,-0.519989
11,2018-10-09,0.070922,0.121204,0.160839,223.639999,227.270004,222.250000,226.869995,226.081161,26891000,3.099991
12,2018-10-10,0.044838,0.104048,0.080283,225.460007,226.350006,216.050003,216.360001,215.607712,41990600,-10.509994
13,2018-10-11,0.047164,0.098919,0.033643,214.520004,219.500000,212.320007,214.449997,213.704346,53124400,-1.910004
14,2018-10-12,0.041669,0.136371,0.114421,220.419998,222.880005,216.839996,222.110001,221.337723,40337900,7.660004
15,2018-10-15,0.007232,0.114294,0.108295,221.160004,221.830002,217.270004,217.360001,216.604233,30791000,-4.750000
16,2018-10-16,0.023632,0.097219,0.061312,218.929993,222.990005,216.759995,222.149994,221.377563,29184000,4.789993
17,2018-10-17,0.121228,0.147455,0.108555,222.300003,222.639999,219.339996,221.190002,220.420914,22885400,-0.959992
18,2018-10-18,-0.005120,0.071888,0.064472,217.860001,219.740005,213.000000,216.020004,215.268890,32581300,-5.169998
19,2018-10-19,0.008488,0.102716,0.074665,218.059998,221.259995,217.429993,219.309998,218.547455,33078700,3.289994
20,2018-10-22,0.395455,0.475000,0.000000,219.789993,223.360001,218.940002,220.649994,219.882782,28792100,1.339996

In [43]:
from scipy.stats.stats import pearsonr   

def get_coor(lrow):
    return pearsonr(lrow['content_score'],lrow['change_close'])[0]

In [44]:
df.iloc[0]['content_score'].dtype

dtype('float64')

In [45]:
for i in range(20):
    print(pcc(np.array(df.iloc[1]['desc_score']),np.array(df.iloc[1]['change_close']))[0])

IndexError: tuple index out of range

In [32]:
def pcc(X, Y):
   # Normalise X and Y
    X -= X.mean(0)
    Y -= Y.mean(0)
   # Standardise X and Y
    X /= X.std(0)
    Y /= Y.std(0)
   # Compute mean product
    return np.mean(X*Y)

In [49]:
pcc(np.array([5.9]),np.array([8.6]))

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys

nan

In [52]:
df['content_score'].corr(df['change_close'])

0.18659629580552536

In [57]:
for i in range(20):
    df.iloc[i]['content_corr']=df.iloc[i]['content_score'].corr(df.iloc[i]['change_close'])

AttributeError: 'numpy.float64' object has no attribute 'corr'